# Regression KNN

In [1]:
from sklearn.datasets import load_boston

boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

## Sample Dataset

In [2]:
import pandas as pd

Rumah = {'pajak rumah': [296.0, 242.0, 242.0, 222.0, 222.0],
         'hektar' : [2.31, 7.07, 7.07, 2.18, 2.18],
        'harga' : [24, 21.6, 34.7, 33.4, 36.2]}

Rumah_df = pd.DataFrame(Rumah)
Rumah_df

pajak rumah  hektar  harga
0        296.0    2.31   24.0
1        242.0    7.07   21.6
2        242.0    7.07   34.7
3        222.0    2.18   33.4
4        222.0    2.18   36.2

Yang saya ambil adalah Tax (pajak rumah) dan INDUS (hektar).

- pajak rumah dan hektar sebagai features.
- harga sebagai target.
Alasan mengambil features tersebut untuk mengetahui harga rumah bila diketahui pajak dan luas rumah nya.

## Features and Target

In [3]:
import numpy as np

X_train = np.array(Rumah_df[['pajak rumah', 'hektar']])
y_train = np.array(Rumah_df['harga'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')

X_train:
[[296.     2.31]
 [242.     7.07]
 [242.     7.07]
 [222.     2.18]
 [222.     2.18]]

y_train: [24.  21.6 34.7 33.4 36.2]


## Training

In [4]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

Mengimport KNeighborsRegressor karena akan menggunakan KNN untuk regression tasks.

## Prediksi 

In [5]:
X_new = np.array([[242., 7.07]])
X_new

array([[242.  ,   7.07]])

In [6]:
y_pred = model.predict(X_new)
y_pred

array([29.9])

Diprediksi pajak rumah 242 dengan hektar 7.07

## Evaluasi

In [7]:
X_test = np.array([[296.0, 2.31], [242.0, 7.07], [242.0, 7.07], [222.0, 2.18], [222.0, 2.18]])
y_test = np.array([27.3, 30.1, 30.1, 35.2, 35.2])

print(f'X_test:\n{X_test}\n')
print(f'y_test: {y_test}')

X_test:
[[296.     2.31]
 [242.     7.07]
 [242.     7.07]
 [222.     2.18]
 [222.     2.18]]

y_test: [27.3 30.1 30.1 35.2 35.2]


In [8]:
y_pred = model.predict(X_test)
y_pred

array([26.76666667, 29.9       , 29.9       , 34.76666667, 34.76666667])

#### Coefficient of Determination atau $R^2$

In [9]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print(f'R-squared: {r_squared}')

R-squared: 0.9848695509937024


R-squared semakin mendekati 1 maka semakin baik dan semakin mendekati 0 maka semakin buruk pula.

#### Mean Absolute Error (MAE) atau Mean Absolute Deviation (MAD)

In [10]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

print(f'MAE: {MAE}')

MAE: 0.3600000000000009


Semakin kecil nilai MEA semakin terlihat baik

#### Mean Squared Error (MSE) atau Mean Squared Deviation (MSD)

In [11]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)

print(f'MSE: {MSE}')

MSE: 0.1480000000000008


Semakin kecil nilai MSE maka semakin baik